### ISSUE TITLE
config not can be updated even with the server off

### ISSUE THREAD

**Issue by comonier** [ElmHoe/AntiBow#10]
does not allow changing the config, example the message:

NotAllowed: '& 7 [& 4Anti & 7- & 4Bow & 7] & 6 & oSorry% PLAYER% & 6 & o, but you''re not allowed to use the bow in the region:% REGION% '

I tried to switch to
NotAllowed: '& 7Bloqued'

I saved, I gave reload, but the plugin goes back to the previous config every time, even updating with the server off

when the server is started and the plugin loaded it returns to the original config and does not allow change, some lock that you have pasted

**Comment by ElmHoe** [comment]
Investigating into this now, thank you.

**Comment by ElmHoe** [comment]
Hello,

This looks to be caused by a menace spelling mistake... 
I've resolved the mistake now, I'll be updating the builds in spigot shortly.

2ab8efc
